### ISSUE TITLE
Not a real check

### ISSUE THREAD

**Issue by yumminova** [nextime/woocommerce-eu-vat-number#5]
First thanks for a great plugin, looks good, integrated good but:

It does not do the job very well.
Its required that one checks the vat number for a specific business name and country.
This plugin now only checks if a number exists, not of the business name is attached to that number.

Strange as http://isvat.appspot.com stated they use the VIES service, i thought the VIES service demands this info do to a request, perhaps viq the api not. Anyway an client can give any valid VAT number for the country they say they are in and we thus dont check the Name, VAT number and country leading to endless fraud posibilities and posible TAX liability. or did i miss a point?

info at beltex.nl

**Comment by nextime** [comment]
@yumminova  please take care that i'm not the author of this plugin. I'm just a customer who have payd to have it and, as it's under gpl and i'm a sort of open source integralist, i've pushed the source code on github to make it free for others.

Anyway, the source code in this repo is very old and probably obsolete now that vat regime in europe is changed starting from 1 january 2015, so, consider it only as a base for developers that want to improve it.

**Comment by yumminova** [comment]
Ok, well it works great except that the check is not real, so that renders it useless. Who creatdd this?

**Comment by yumminova** [comment]
It might be handy info for others as well

------ Origineel bericht ------
Van: "Franco (nextime) Lanza" <notifications@github.com>
Aan: "nextime/woocommerce-eu-vat-number" 
<woocommerce-eu-vat-number@noreply.github.com>
CC: "yumminova" <info@yumminova.eu>
Verzonden: 28-6-2015 1:21:46
Onderwerp: Re: [woocommerce-eu-vat-number] Not a real check (#5)
